services:
  # DB 서비스 (동일)
  db:
    image: mysql:8.0
    container_name: tiebreak-db-dev
    ports:
      - "3307:3306"  # 포트를 3307로 변경
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tiebreak_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 개발용 API 서버 (Spring Boot DevTools)
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api-server:/app
      - /app/target # target 폴더는 동기화에서 제외
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 30s
      retries: 5

  # 개발용 데이터 수집 서버 (Flask 개발 모드)
  data-collector:
    build: ./data-collector
    ports:
      - "5001:5000"
    volumes:
      - ./data-collector:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      timeout: 30s
      retries: 5

  # 개발용 프론트엔드 (Vite 개발 서버)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # node_modules는 동기화에서 제외
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      api-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      timeout: 30s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  db-data:
